### ISSUE TITLE
Simple Contacts Pro: VCF export drops most fields when Signal entries included

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/General-Discussion#115] opened 2019-07-09 23:36 UTC
I am running Simple Contacts Pro v6.3.2 on Nexus 5 phone with Android 6.0.1. I also use Signal Private Messenger.

When I use the Simple Contacts Pro "Export contacts to a .vcf file" feature, the Export Contacts dialog offers me three contact sources to include: Signal, my Google account email address, and phone storage. Signal as a source is disabled by default. If I accept the defaults, I get the expected VCF file. But, if I add Signal as a source, I then get a VCF file that is missing all contact fields except for contact names and photos. There are NO phone numbers, addresses, email addresses, notes, etc. This is a strange bug.

**Comment by alcoolfire** [comment] 2019-07-09 23:44
Sorry, I got that backwards. With Signal entries included, all fields are included in the VCF file. With Signal entries excluded (the default), only names and photos are included.

**Comment by tibbi** [comment] 2019-07-10 06:43
duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/377 . Report new issues there please, not everything at the General Discussion

**Closed by tibbi** 2019-07-10 06:43 UTC

**Comment by alcoolfire** [comment] 2019-07-10 07:09
My sincere apologies. I totally failed to notice I'd been reporting to the wrong topic :-(
