### ISSUE TITLE
Move translations to more appropriate system

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/General-Discussion#88] opened 2018-09-29 15:55 UTC
I would like to contribute to app by translating it to my language but I find using Github quite hard for this job.

Services you can use for translation system;
Weblate
Transifex

**Comment by tibbi** [comment] 2018-09-29 20:06
duplicate of #3 . Maybe some other system would be easier, but it would cost me an awful lot of time to keep copy pasting things. Once you create a pull request, github is really easy to work with.

**Closed by tibbi** 2018-09-29 20:06 UTC
