### ISSUE TITLE
Maximum limit of concurrent alarms 500 reached

### ISSUE THREAD

**Issue by t0b1p** [SimpleMobileTools/General-Discussion#169] opened 2021-11-14 10:31 UTC
See screenshot, what can I do? It is a constant overlay and bothers until I force stop the app.
![Screenshot_2021-11-09-08-55-55-08](https://user-images.githubusercontent.com/92738632/141677258-53e5af10-4077-44ab-95d3-b3ed63acf746.jpg)

**Comment by tibbi** [comment] 2021-11-14 10:58
duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/1037

**Closed by tibbi** 2021-11-14 10:58 UTC
