### ISSUE TITLE
Translation Sites

### ISSUE THREAD

**Issue by RickyM7** [SimpleMobileTools/General-Discussion#137] opened 2020-10-25 16:19 UTC
It would be great if your projects were added to some translation site, such as Crowdin, WebLate, POEditor or Transifex. These sites have free plans and make the work of translators much easier.

**Comment by tibbi** [comment] 2020-10-25 17:35
But they make my work a lot harder by copypasting everything. The vast majority of things is translated properly already, not that much will be added in the future. Duplicate of #3

**Closed by tibbi** 2020-10-25 17:35 UTC

**Comment by RickyM7** [comment] 2020-10-25 18:03
Sorry for the duplicate, I search before posting but I ended up not finding the issue #3. About the more work, I think there are some plugins for github that facilitates the passage of translations on these sites to the repo, the problem is that I do not know where to find them, I just saw a dev of an application commenting on it.

**Comment by tibbi** [comment] 2020-10-25 18:58
I dont like overengineering things, github translations are working just fine

**Comment by RickyM7** [comment] 2020-10-25 19:07
Thanks again for the answers.
