### ISSUE TITLE
[Feature Request] Metadata Cleaner

### ISSUE THREAD

**Issue by Flam3z** [SimpleMobileTools/General-Discussion#134] opened 2020-08-16 15:35 UTC
If its possible to implement this feature by default within simple gallery and if possible I would surely use it daily for privacy reasons.

**Comment by tibbi** [comment] 2020-08-16 16:20
ye an EXIF editor with cleaner is on the roadmap for the gallery, duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/282

**Closed by tibbi** 2020-08-16 16:20 UTC
