### ISSUE TITLE
simple music player: Playback of the queue stops after each track.

### ISSUE THREAD

**Issue by lars-vom-mars-x** [SimpleMobileTools/General-Discussion#143] opened 2021-01-12 12:45 UTC
I put some titles in my queue. Go to the queue. Klick one title, but not the last in the queue. Title is playing. But it stops after this title. 
How can i play the whole queue?
Bests, Lars

**Comment by tibbi** [comment] 2021-01-12 16:22
duplicate of https://github.com/SimpleMobileTools/Simple-Music-Player/issues/255

**Closed by tibbi** 2021-01-12 16:22 UTC
